language: cpp

## Use the container-based infrastructure
sudo: false

matrix:
  include:
    - compiler: gcc
      env: REAL_CC=gcc-4.8     REAL_CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libstdc++6-4.8-dbg
            - build-essential
            - cmake
            - libportmidi-dev
            - libsqlite3-0
            - libsqlite3-dev
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libboost-date-time-dev
            - libboost-thread-dev
            - libboost-system-dev
    - compiler: gcc
      env: REAL_CC=gcc-4.8     REAL_CXX="g++-4.8 -std=gnu++11"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-4.8
            - libstdc++6-4.8-dbg
            - build-essential
            - cmake
            - libportmidi-dev
            - libsqlite3-0
            - libsqlite3-dev
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libboost-date-time1.54-dev
            - libboost-thread1.54-dev
            - libboost-system1.54-dev

before_install:
    - export CC="${REAL_CC}" CXX="${REAL_CXX}"

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles"  ..

script:
  - make

after_success:
  - ./bin/testlib

notifications:
  email:
    - s.cecilio@gmail.com
