language: cpp

compiler: gcc

## Use the container-based infrastructure
sudo: false

env:
  - REAL_CC=gcc-4.8     REAL_CXX=g++-4.8
  - REAL_CC=gcc-4.8     REAL_CXX="g++-4.8 -std=gnu++11"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++6-4.8-dbg
      - build-essential
      - cmake
      - libboost-date-time-dev
      - libboost-thread-dev
      - libboost-system-dev
      - libportmidi-dev
      - libsqlite3-0
      - libsqlite3-dev
      - libfreetype6-dev
      - libpng++-dev
      - zlib1g-dev
      - libwxgtk3.0-dev
      - libunittest++-dev

before_install:
    - export CC="${REAL_CC}" CXX="${REAL_CXX}"

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles"  ..

script:
  - make

after_success:
  - ./bin/testlib

notifications:
  email:
    - s.cecilio@gmail.com
